### ISSUE TITLE
Uncaught ReferenceError: Chartkick is not defined error

### ISSUE THREAD

**Issue by lenfree** [buren/chartkick-ex#18]
Hi @buren , I am trying to make this work in Elixir/Phoenix 1.4 and getting this error

```
Uncaught ReferenceError: Chartkick is not defined error
```

I followed README to add below to my mix.exs file:

```
{:chartkick, "~>0.4.0"}
```

and added below to my template file. 

```
data = Poison.encode!([[175, 60], [190, 80], [180, 75]])
Chartkick.line_chart data
```

Did I miss something? Sorry, I am a newbie.

**Comment by lenfree** [comment]
Actually, I found out that I have to have the javascript bit in head tag as shown in example. Closing this now. Thanks!

**Comment by buren** [comment]
Cool 👍
