### ISSUE TITLE
Not working inside LiveView phoenix

### ISSUE THREAD

**Issue by ehayun** [buren/chartkick-ex#19]
Great package. Thanks
When I put it on a regular view it works fine but what I put it in a liveView render it display the chart for a split of a sec and then just put "Loading..."
I believe that the LiveView is taking control but I don't know how to solve it

**Comment by jesuiswu** [comment]
I think it should implement live view hooks

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-js-interop-and-client-controlled-dom

**Comment by ehayun** [comment]
I guess you are right. Thanks
