### ISSUE TITLE
Project development

### ISSUE THREAD

**Issue by mbenatti** [buren/chartkick-ex#2]
This project are abandoned? 
plus I have a question: 
1)This project is integrated with phoenix framework??

**Comment by buren** [comment]
Hi @mbenatti! I haven't looked or used this project in a while. 

This is meant to be a thin wrapper around [chartkick.js](https://github.com/ankane/chartkick.js) and the public API tries to mirror the [Ruby wrapper](https://github.com/ankane/chartkick) (written by the same author as chartkick.js). 

This package can definitely be used with the Phoenix framework. Generally it should be possible to use this package in any Elixir project. I actually have a demo application using this package with Phoenix, see https://github.com/buren/chartkick-phoenix-example or more specifically [this commit](https://github.com/buren/chartkick-phoenix-example/commit/3f096ea3717f773246679112a7de4f8be762fd74).

**Comment by buren** [comment]
https://github.com/buren/chartkick-ex/pull/3
