### ISSUE TITLE
Support deferring js

### ISSUE THREAD

**Issue by danielzfranklin** [buren/chartkick-ex#37]
I'd prefer to render the rest of the page first, load Chartkick, and then render the charts. This would remove the requirement to load Chartkick in the head.

I think this could by changing the generated js to something like

```javascript
(function() {
  function render() {
    // .. existing generated js
  }

  if (window.Chartkick !== undefined) {
    render()
  } else {
    window.addEventListener("chartkick-loaded", render);
  }
}(();
```

and also changing chartkick.js to emit that event.

**Comment by buren** [comment]
Interesting!

Since this would require changes in [chartkick.js](https://github.com/ankane/chartkick). It would be best to first head over there to get the `chartkick-loaded` event implemented. (I'm not the maintainer of chartkick.js.)

Thanks a lot!

**Comment by danielzfranklin** [comment]
Great news @buren! chartkick.js already implemented this to work better with chartkick ruby. The javascript generated by the ruby code for chartkick 4 looks like so

```js
    (function() {
            if (document.documentElement.hasAttribute("data-turbolinks-preview")) return;
            var createChart = function() { #{createjs} };
            if ("Chartkick" in window) {
              createChart();
            } else {
              window.addEventListener("chartkick:load", createChart, true);
            }
          })();
```

https://github.com/ankane/chartkick/commit/49520f95564d9a27616d0d2b4dec56cfe6019837#diff-00f358b1ba9cc28d89dd12efd12596df0d2dd3c281ad68d57a27b85aa5e9c0f4R107

I can work on a PR if copying the approach used by chartkick ruby seems reasonable to you?

**Comment by buren** [comment]
That definitely looks like a way forward 👍
I've tried to follow what ankanke does in both chartkick.js and the wrappers maintained by him.

Would love a PR! 🌟 

Thanks @danielzfranklin!

**Comment by danielzfranklin** [comment]
Are the functions like chartkick_create_js part of the public api?

**Comment by buren** [comment]
No, I wouldn't consider `chartkick_create_js` public api.

**Comment by buren** [comment]
Another thing I saw, following the code you (@danielzfranklin) linked, is that the `defer` option is not needed anymore and that it's now the default behaviour (commit https://github.com/ankane/chartkick/commit/49520f95564d9a27616d0d2b4dec56cfe6019837).
