### ISSUE TITLE
Livebook support

### ISSUE THREAD

**Issue by arrowcircle** [buren/chartkick-ex#51]
Hi there! Thanks a lot for the library. Do you happen to know if it's possible to use chartkick-ex with livebook?

**Comment by buren** [comment]
Hi @arrowcircle,

I'm glad you find the library useful!

I don't know to be honest. I haven't used Livebook.

p.s since this is not an issue with the library per se I will close this issue. If you test it with Livebook feel free to post an update here for others to know if it works (or not).
